Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Information

TestObj:
  receipt: Oz-Ware Purchase Invoice
  date: 2007-08-06T00:00:00.0000000
  customer:
    given: Dorothy
    family: Gale
  items:
  - part_no: A4786
    descrip: Water Bucket (Filled)
    price: 1.47
    quantity: 4
  - part_no: E1628
    descrip: High Heeled "Ruby" Slippers
    price: 100.27
    quantity: 1
  bill_to: &o0
    street: >-
      123 Tornado Alley

      Suite 16
    city: East Westville
    state: KS
  ship_to: *o0
  specialDelivery: >-
    Follow the Yellow Brick
  
    Road to the Emerald City.
  
    Pay no attention to the
  
    man behind the curtain.
  